//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContingenciaOperador {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosContingencia {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosContingencia() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContingenciaOperador.RecursosContingencia", typeof(RecursosContingencia).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        internal static string Alterno {
            get {
                return ResourceManager.GetString("Alterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Ring.
        /// </summary>
        internal static string AnularDerecho {
            get {
                return ResourceManager.GetString("AnularDerecho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Ring.
        /// </summary>
        internal static string AnularIzquierdo {
            get {
                return ResourceManager.GetString("AnularIzquierdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodigoTramite.
        /// </summary>
        internal static string CodigoTramite {
            get {
                return ResourceManager.GetString("CodigoTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss,f.
        /// </summary>
        internal static string FormatoFecha {
            get {
                return ResourceManager.GetString("FormatoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO-FMR.
        /// </summary>
        internal static string FormatoISO {
            get {
                return ResourceManager.GetString("FormatoISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdClienteRnec.
        /// </summary>
        internal static string IdClienteRnec {
            get {
                return ResourceManager.GetString("IdClienteRnec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Index.
        /// </summary>
        internal static string IndiceDerecho {
            get {
                return ResourceManager.GetString("IndiceDerecho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Index.
        /// </summary>
        internal static string IndiceIzquierdo {
            get {
                return ResourceManager.GetString("IndiceIzquierdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        internal static string Ip {
            get {
                return ResourceManager.GetString("Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC.
        /// </summary>
        internal static string Mac {
            get {
                return ResourceManager.GetString("Mac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Middle.
        /// </summary>
        internal static string MedioDerecho {
            get {
                return ResourceManager.GetString("MedioDerecho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Middle.
        /// </summary>
        internal static string MedioIzquierdo {
            get {
                return ResourceManager.GetString("MedioIzquierdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Pinky.
        /// </summary>
        internal static string MeniqueDerecho {
            get {
                return ResourceManager.GetString("MeniqueDerecho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Pinky.
        /// </summary>
        internal static string MeniqueIzquierdo {
            get {
                return ResourceManager.GetString("MeniqueIzquierdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se logro consultar Ares.
        /// </summary>
        internal static string MensajeAres {
            get {
                return ResourceManager.GetString("MensajeAres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es requerido el campo Nuip.
        /// </summary>
        internal static string MensajeCampoNUIP {
            get {
                return ResourceManager.GetString("MensajeCampoNUIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es requerido el campo NumeroHuellasCotejamiento.
        /// </summary>
        internal static string MensajeCampoNumeroHuellasCotejamiento {
            get {
                return ResourceManager.GetString("MensajeCampoNumeroHuellasCotejamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es requerido el campo ScoreReferencia.
        /// </summary>
        internal static string MensajeCampoScoreReferencia {
            get {
                return ResourceManager.GetString("MensajeCampoScoreReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidato no encontrado.
        /// </summary>
        internal static string MensajeCandidateNotFound {
            get {
                return ResourceManager.GetString("MensajeCandidateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asociado al dedo.
        /// </summary>
        internal static string MensajeDedoFormato {
            get {
                return ResourceManager.GetString("MensajeDedoFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de Huella Errado.
        /// </summary>
        internal static string MensajeFormatoHuella {
            get {
                return ResourceManager.GetString("MensajeFormatoHuella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de Template Errado.
        /// </summary>
        internal static string MensajeFormatoTemplate {
            get {
                return ResourceManager.GetString("MensajeFormatoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rango de Huellas debe estar entre 0 y 10.
        /// </summary>
        internal static string MensajeHuellas {
            get {
                return ResourceManager.GetString("MensajeHuellas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen dedos repetidos en la lista.
        /// </summary>
        internal static string MensajeHuellasDuplicadas {
            get {
                return ResourceManager.GetString("MensajeHuellasDuplicadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es requerido el nombre de la Muestra.
        /// </summary>
        internal static string MensajeNombreMuestra {
            get {
                return ResourceManager.GetString("MensajeNombreMuestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es requerido el nombre del template.
        /// </summary>
        internal static string MensajeNombreTemplate {
            get {
                return ResourceManager.GetString("MensajeNombreTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se logro consultar el Operador.
        /// </summary>
        internal static string MensajeOperador {
            get {
                return ResourceManager.GetString("MensajeOperador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se logro consultar la réplica de la RNEC.
        /// </summary>
        internal static string MensajeRNEC {
            get {
                return ResourceManager.GetString("MensajeRNEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rango de Templates debe estar entre 0 y 10.
        /// </summary>
        internal static string MensajeTemplate {
            get {
                return ResourceManager.GetString("MensajeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen dedos repetidos en la lista.
        /// </summary>
        internal static string MensajeTemplateDuplicados {
            get {
                return ResourceManager.GetString("MensajeTemplateDuplicados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Required.
        /// </summary>
        internal static string NoRequerido {
            get {
                return ResourceManager.GetString("NoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Thumb.
        /// </summary>
        internal static string PulgarDerecho {
            get {
                return ResourceManager.GetString("PulgarDerecho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Thumb.
        /// </summary>
        internal static string PulgarIzquierdo {
            get {
                return ResourceManager.GetString("PulgarIzquierdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Requerido {
            get {
                return ResourceManager.GetString("Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es requerido el campo.
        /// </summary>
        internal static string ValidacionCampoCliente {
            get {
                return ResourceManager.GetString("ValidacionCampoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es requerida la huella.
        /// </summary>
        internal static string ValidacionHuella {
            get {
                return ResourceManager.GetString("ValidacionHuella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es requerida el template.
        /// </summary>
        internal static string ValidacionTemplate {
            get {
                return ResourceManager.GetString("ValidacionTemplate", resourceCulture);
            }
        }
    }
}
