//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContingenciaOperador.Entidades {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContingenciaOperador.Entidades.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Ring.
        /// </summary>
        internal static string AnularDerecho {
            get {
                return ResourceManager.GetString("AnularDerecho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Ring.
        /// </summary>
        internal static string AnularIzquierdo {
            get {
                return ResourceManager.GetString("AnularIzquierdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Index.
        /// </summary>
        internal static string IndiceDerecho {
            get {
                return ResourceManager.GetString("IndiceDerecho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Index.
        /// </summary>
        internal static string IndiceIzquierdo {
            get {
                return ResourceManager.GetString("IndiceIzquierdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Middle.
        /// </summary>
        internal static string MedioDerecho {
            get {
                return ResourceManager.GetString("MedioDerecho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Middle.
        /// </summary>
        internal static string MedioIzquierdo {
            get {
                return ResourceManager.GetString("MedioIzquierdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Pinky.
        /// </summary>
        internal static string MeniqueDerecho {
            get {
                return ResourceManager.GetString("MeniqueDerecho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Pinky.
        /// </summary>
        internal static string MeniqueIzquierdo {
            get {
                return ResourceManager.GetString("MeniqueIzquierdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Thumb.
        /// </summary>
        internal static string PulgarDerecho {
            get {
                return ResourceManager.GetString("PulgarDerecho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Thumb.
        /// </summary>
        internal static string PulgarIzquierdo {
            get {
                return ResourceManager.GetString("PulgarIzquierdo", resourceCulture);
            }
        }
    }
}
