//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContingenciaOperador.WSSecurIDMatcher {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSSecurIDMatcher.WSSecurIDMatcherSoap")]
    public interface WSSecurIDMatcherSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MatcherServices_V0R1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CandidateType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicHeaderResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicPmt2ResponseType))]
        ContingenciaOperador.WSSecurIDMatcher.AuthenticatePersonPmt2Response MatcherServices_V0R1(ContingenciaOperador.WSSecurIDMatcher.WSSecurIDMatcherEntry DataEntry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MatcherServices_V0R1", ReplyAction="*")]
        System.Threading.Tasks.Task<ContingenciaOperador.WSSecurIDMatcher.AuthenticatePersonPmt2Response> MatcherServices_V0R1Async(ContingenciaOperador.WSSecurIDMatcher.WSSecurIDMatcherEntry DataEntry);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WSSecurIDMatcherEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private KeyValueOfstringstring[] diccionarioolimpiaField;
        
        private string clientIdField;
        
        private string nUTField;
        
        private string operatorIdField;
        
        private string aplicantIdField;
        
        private FingerPrintGroup[] fingerGroupField;
        
        private UserInfoGroup userInfoField;
        
        private PosicionGroup posicionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public KeyValueOfstringstring[] Diccionarioolimpia {
            get {
                return this.diccionarioolimpiaField;
            }
            set {
                this.diccionarioolimpiaField = value;
                this.RaisePropertyChanged("Diccionarioolimpia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("ClientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NUT {
            get {
                return this.nUTField;
            }
            set {
                this.nUTField = value;
                this.RaisePropertyChanged("NUT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OperatorId {
            get {
                return this.operatorIdField;
            }
            set {
                this.operatorIdField = value;
                this.RaisePropertyChanged("OperatorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AplicantId {
            get {
                return this.aplicantIdField;
            }
            set {
                this.aplicantIdField = value;
                this.RaisePropertyChanged("AplicantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public FingerPrintGroup[] FingerGroup {
            get {
                return this.fingerGroupField;
            }
            set {
                this.fingerGroupField = value;
                this.RaisePropertyChanged("FingerGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public UserInfoGroup UserInfo {
            get {
                return this.userInfoField;
            }
            set {
                this.userInfoField = value;
                this.RaisePropertyChanged("UserInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public PosicionGroup Posicion {
            get {
                return this.posicionField;
            }
            set {
                this.posicionField = value;
                this.RaisePropertyChanged("Posicion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KeyValueOfstringstring : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/pmt2/xsd/1.0")]
    public partial class ErrorPmt2Type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EnumPmt2CodeErrorType codeErrorPmt2Field;
        
        private string libelErrorPmt2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EnumPmt2CodeErrorType codeErrorPmt2 {
            get {
                return this.codeErrorPmt2Field;
            }
            set {
                this.codeErrorPmt2Field = value;
                this.RaisePropertyChanged("codeErrorPmt2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string libelErrorPmt2 {
            get {
                return this.libelErrorPmt2Field;
            }
            set {
                this.libelErrorPmt2Field = value;
                this.RaisePropertyChanged("libelErrorPmt2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/pmt2/xsd/1.0")]
    public enum EnumPmt2CodeErrorType {
        
        /// <remarks/>
        NOT_AUTHORIZED,
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        FAILURE,
        
        /// <remarks/>
        CandidateNotFound,
        
        /// <remarks/>
        CandidateFound,
        
        /// <remarks/>
        CandidateFoundPartialFingers,
        
        /// <remarks/>
        CandidateNotAuthorized,
        
        /// <remarks/>
        CandidateNotAuthorizedByAge,
        
        /// <remarks/>
        CandidateFoundInvalidFingers,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Error While Saving the Transaction")]
        ErrorWhileSavingtheTransaction,
        
        /// <remarks/>
        InvalidInputParameter,
        
        /// <remarks/>
        InvalidOperatorId,
        
        /// <remarks/>
        OperatorDisabled,
        
        /// <remarks/>
        InvalidNut,
        
        /// <remarks/>
        InvalidNuipNip,
        
        /// <remarks/>
        InvalidFingerId,
        
        /// <remarks/>
        FingerDataNotEnough,
        
        /// <remarks/>
        InvalidClientId,
        
        /// <remarks/>
        ClientDisabled,
        
        /// <remarks/>
        InvalidFingerPrintFormat,
        
        /// <remarks/>
        FingerPrintFormatNotAuthorized,
        
        /// <remarks/>
        InvalidClientOperatorLink,
        
        /// <remarks/>
        ClientOperatorLinkDisabled,
        
        /// <remarks/>
        InactiveAgreement,
        
        /// <remarks/>
        ExpiredAgreement,
        
        /// <remarks/>
        FingerPrintNotFound,
        
        /// <remarks/>
        FingerPrint1NotFound,
        
        /// <remarks/>
        FingerPrint2NotFound,
        
        /// <remarks/>
        FingerPrint3NotFound,
        
        /// <remarks/>
        FingerPrint4NotFound,
        
        /// <remarks/>
        FingerPrint5NotFound,
        
        /// <remarks/>
        FingerPrint6NotFound,
        
        /// <remarks/>
        FingerPrint7NotFound,
        
        /// <remarks/>
        FingerPrint8NotFound,
        
        /// <remarks/>
        FingerPrint9NotFound,
        
        /// <remarks/>
        FingerPrint10NotFound,
        
        /// <remarks/>
        FingerPrintError,
        
        /// <remarks/>
        FingerPrintConvertError,
        
        /// <remarks/>
        FingerPrintConvertToISOError,
        
        /// <remarks/>
        FingerPrintConvertToANSIError,
        
        /// <remarks/>
        GeneralError,
        
        /// <remarks/>
        MemoryError,
        
        /// <remarks/>
        DiskSpaceError,
        
        /// <remarks/>
        CommunicationError,
        
        /// <remarks/>
        DataBaseError,
        
        /// <remarks/>
        UnknownError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/mbss/generic/xsd/1.0")]
    public partial class SampleReferenceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int registrationIDField;
        
        private bool registrationIDFieldSpecified;
        
        private int printSetIDField;
        
        private bool printSetIDFieldSpecified;
        
        private int irisSetIDField;
        
        private bool irisSetIDFieldSpecified;
        
        private int faceSetIDField;
        
        private bool faceSetIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RegistrationID {
            get {
                return this.registrationIDField;
            }
            set {
                this.registrationIDField = value;
                this.RaisePropertyChanged("RegistrationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegistrationIDSpecified {
            get {
                return this.registrationIDFieldSpecified;
            }
            set {
                this.registrationIDFieldSpecified = value;
                this.RaisePropertyChanged("RegistrationIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PrintSetID {
            get {
                return this.printSetIDField;
            }
            set {
                this.printSetIDField = value;
                this.RaisePropertyChanged("PrintSetID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrintSetIDSpecified {
            get {
                return this.printSetIDFieldSpecified;
            }
            set {
                this.printSetIDFieldSpecified = value;
                this.RaisePropertyChanged("PrintSetIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IrisSetID {
            get {
                return this.irisSetIDField;
            }
            set {
                this.irisSetIDField = value;
                this.RaisePropertyChanged("IrisSetID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IrisSetIDSpecified {
            get {
                return this.irisSetIDFieldSpecified;
            }
            set {
                this.irisSetIDFieldSpecified = value;
                this.RaisePropertyChanged("IrisSetIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int FaceSetID {
            get {
                return this.faceSetIDField;
            }
            set {
                this.faceSetIDField = value;
                this.RaisePropertyChanged("FaceSetID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FaceSetIDSpecified {
            get {
                return this.faceSetIDFieldSpecified;
            }
            set {
                this.faceSetIDFieldSpecified = value;
                this.RaisePropertyChanged("FaceSetIDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/mbss/generic/xsd/1.0")]
    public partial class PersonToPersonAuthenticateErrorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EnumPersonToPersonAuthenticateErrorType typeField;
        
        private SampleReferenceType sampleReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EnumPersonToPersonAuthenticateErrorType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SampleReferenceType SampleReference {
            get {
                return this.sampleReferenceField;
            }
            set {
                this.sampleReferenceField = value;
                this.RaisePropertyChanged("SampleReference");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/mbss/generic/xsd/1.0")]
    public enum EnumPersonToPersonAuthenticateErrorType {
        
        /// <remarks/>
        NO_ERROR,
        
        /// <remarks/>
        ERROR_NULL_PARAMETER,
        
        /// <remarks/>
        ERROR_MEMORY_ALLOCATION_FAILED,
        
        /// <remarks/>
        ERROR_ASSERTION_FAILED,
        
        /// <remarks/>
        ERROR_PROTECTION,
        
        /// <remarks/>
        INVALID_PARAMETER,
        
        /// <remarks/>
        INVALID_CONFIGURATION_BLOCK,
        
        /// <remarks/>
        ERROR_INTERNAL,
        
        /// <remarks/>
        ERROR_INVALID_CFV_DATA,
        
        /// <remarks/>
        ERROR_INVALID_CFV_VERSION,
        
        /// <remarks/>
        ERROR_IMAGE_DECOMPRESSION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/pmt2/xsd/1.0")]
    public partial class CandidateAlphaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string alphaIdField;
        
        private string alphaValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AlphaId {
            get {
                return this.alphaIdField;
            }
            set {
                this.alphaIdField = value;
                this.RaisePropertyChanged("AlphaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AlphaValue {
            get {
                return this.alphaValueField;
            }
            set {
                this.alphaValueField = value;
                this.RaisePropertyChanged("AlphaValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/mbss/generic/xsd/1.0")]
    public partial class PersonPrintIdType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int registrationIDField;
        
        private int sampleIDField;
        
        private int positionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RegistrationID {
            get {
                return this.registrationIDField;
            }
            set {
                this.registrationIDField = value;
                this.RaisePropertyChanged("RegistrationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SampleID {
            get {
                return this.sampleIDField;
            }
            set {
                this.sampleIDField = value;
                this.RaisePropertyChanged("SampleID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("Position");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/mbss/generic/xsd/1.0")]
    public partial class BiometricItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int subscoreField;
        
        private int transUField;
        
        private int transVField;
        
        private int rotation64Field;
        
        private int dilatationField;
        
        private int crampingXField;
        
        private int crampingYField;
        
        private PersonPrintIdType personSearchIdField;
        
        private PersonPrintIdType personRefIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Subscore {
            get {
                return this.subscoreField;
            }
            set {
                this.subscoreField = value;
                this.RaisePropertyChanged("Subscore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TransU {
            get {
                return this.transUField;
            }
            set {
                this.transUField = value;
                this.RaisePropertyChanged("TransU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TransV {
            get {
                return this.transVField;
            }
            set {
                this.transVField = value;
                this.RaisePropertyChanged("TransV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Rotation64 {
            get {
                return this.rotation64Field;
            }
            set {
                this.rotation64Field = value;
                this.RaisePropertyChanged("Rotation64");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Dilatation {
            get {
                return this.dilatationField;
            }
            set {
                this.dilatationField = value;
                this.RaisePropertyChanged("Dilatation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int crampingX {
            get {
                return this.crampingXField;
            }
            set {
                this.crampingXField = value;
                this.RaisePropertyChanged("crampingX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int crampingY {
            get {
                return this.crampingYField;
            }
            set {
                this.crampingYField = value;
                this.RaisePropertyChanged("crampingY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public PersonPrintIdType personSearchId {
            get {
                return this.personSearchIdField;
            }
            set {
                this.personSearchIdField = value;
                this.RaisePropertyChanged("personSearchId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public PersonPrintIdType personRefId {
            get {
                return this.personRefIdField;
            }
            set {
                this.personRefIdField = value;
                this.RaisePropertyChanged("personRefId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/mbss/generic/xsd/1.0")]
    public partial class BiometricGroupType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GroupTypeType groupTypeField;
        
        private int groupScoreField;
        
        private BiometricItemType[] biometricItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GroupTypeType GroupType {
            get {
                return this.groupTypeField;
            }
            set {
                this.groupTypeField = value;
                this.RaisePropertyChanged("GroupType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int GroupScore {
            get {
                return this.groupScoreField;
            }
            set {
                this.groupScoreField = value;
                this.RaisePropertyChanged("GroupScore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BiometricItem", Order=2)]
        public BiometricItemType[] BiometricItem {
            get {
                return this.biometricItemField;
            }
            set {
                this.biometricItemField = value;
                this.RaisePropertyChanged("BiometricItem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/mbss/generic/xsd/1.0")]
    public enum GroupTypeType {
        
        /// <remarks/>
        FINGER,
        
        /// <remarks/>
        PALM,
        
        /// <remarks/>
        FACE,
        
        /// <remarks/>
        IRIS,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CandidatePmt2Type))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/mbss/generic/xsd/1.0")]
    public partial class CandidateType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pINField;
        
        private int scoreField;
        
        private DecisionType decisionField;
        
        private BiometricGroupType[] biometricGroupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PIN {
            get {
                return this.pINField;
            }
            set {
                this.pINField = value;
                this.RaisePropertyChanged("PIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
                this.RaisePropertyChanged("score");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public DecisionType Decision {
            get {
                return this.decisionField;
            }
            set {
                this.decisionField = value;
                this.RaisePropertyChanged("Decision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BiometricGroup", Order=3)]
        public BiometricGroupType[] BiometricGroup {
            get {
                return this.biometricGroupField;
            }
            set {
                this.biometricGroupField = value;
                this.RaisePropertyChanged("BiometricGroup");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/mbss/generic/xsd/1.0")]
    public enum DecisionType {
        
        /// <remarks/>
        HIT,
        
        /// <remarks/>
        NO_HIT,
        
        /// <remarks/>
        NOT_FOUND,
        
        /// <remarks/>
        UNKNOWN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/pmt2/xsd/1.0")]
    public partial class CandidatePmt2Type : CandidateType {
        
        private CandidateAlphaType[] candidateAlphaListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CandidateAlphaList", Order=0)]
        public CandidateAlphaType[] CandidateAlphaList {
            get {
                return this.candidateAlphaListField;
            }
            set {
                this.candidateAlphaListField = value;
                this.RaisePropertyChanged("CandidateAlphaList");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/pmt2/xsd/1.0")]
    public partial class AuthenticationIDType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string searchCandidateIdField;
        
        private string authenticationIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SearchCandidateId {
            get {
                return this.searchCandidateIdField;
            }
            set {
                this.searchCandidateIdField = value;
                this.RaisePropertyChanged("SearchCandidateId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AuthenticationId {
            get {
                return this.authenticationIdField;
            }
            set {
                this.authenticationIdField = value;
                this.RaisePropertyChanged("AuthenticationId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/mbss/generic/xsd/1.0")]
    public partial class ErrorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EnumCodeErrorType codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EnumCodeErrorType code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/mbss/generic/xsd/1.0")]
    public enum EnumCodeErrorType {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        GENERAL_FAILURE,
        
        /// <remarks/>
        DUPLICATE_KEY,
        
        /// <remarks/>
        KEY_NOT_FOUND,
        
        /// <remarks/>
        INVALID_INPUT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/mbss/generic/xsd/1.0")]
    public partial class InfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/mbss/generic/xsd/1.0")]
    public partial class StepDurationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string stepNameField;
        
        private int timestampStartField;
        
        private int timestampStopField;
        
        private int durationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StepName {
            get {
                return this.stepNameField;
            }
            set {
                this.stepNameField = value;
                this.RaisePropertyChanged("StepName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TimestampStart {
            get {
                return this.timestampStartField;
            }
            set {
                this.timestampStartField = value;
                this.RaisePropertyChanged("TimestampStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TimestampStop {
            get {
                return this.timestampStopField;
            }
            set {
                this.timestampStopField = value;
                this.RaisePropertyChanged("TimestampStop");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("Duration");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/mbss/generic/xsd/1.0")]
    public partial class ElapsedTimeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int totalTimeField;
        
        private StepDurationType[] stepDurationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TotalTime {
            get {
                return this.totalTimeField;
            }
            set {
                this.totalTimeField = value;
                this.RaisePropertyChanged("TotalTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StepDuration", Order=1)]
        public StepDurationType[] StepDuration {
            get {
                return this.stepDurationField;
            }
            set {
                this.stepDurationField = value;
                this.RaisePropertyChanged("StepDuration");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasicHeaderPmt2ResponseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/mbss/generic/xsd/1.0")]
    public partial class BasicHeaderResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIdField;
        
        private ElapsedTimeType elapsedTimeField;
        
        private InfoType[] infoField;
        
        private ErrorType errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ElapsedTimeType ElapsedTime {
            get {
                return this.elapsedTimeField;
            }
            set {
                this.elapsedTimeField = value;
                this.RaisePropertyChanged("ElapsedTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Info", Order=2)]
        public InfoType[] Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("Info");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ErrorType error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/pmt2/xsd/1.0")]
    public partial class BasicHeaderPmt2ResponseType : BasicHeaderResponseType {
        
        private EnumPmt2CodeErrorType resultField;
        
        private string operatorIdField;
        
        private string clientIdField;
        
        private AuthenticationIDType authenticationNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EnumPmt2CodeErrorType Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OperatorId {
            get {
                return this.operatorIdField;
            }
            set {
                this.operatorIdField = value;
                this.RaisePropertyChanged("OperatorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("ClientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AuthenticationIDType AuthenticationNumber {
            get {
                return this.authenticationNumberField;
            }
            set {
                this.authenticationNumberField = value;
                this.RaisePropertyChanged("AuthenticationNumber");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthenticatePmt2ResponseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/pmt2/xsd/1.0")]
    public partial class BasicPmt2ResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BasicHeaderPmt2ResponseType basicHeaderResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BasicHeaderPmt2ResponseType BasicHeaderResponse {
            get {
                return this.basicHeaderResponseField;
            }
            set {
                this.basicHeaderResponseField = value;
                this.RaisePropertyChanged("BasicHeaderResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.morpho.com/pmt2/xsd/1.0")]
    public partial class AuthenticatePmt2ResponseType : BasicPmt2ResponseType {
        
        private CandidatePmt2Type[] candidateListField;
        
        private PersonToPersonAuthenticateErrorType[] errorsField;
        
        private ErrorPmt2Type errorPmt2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Candidate", IsNullable=false)]
        public CandidatePmt2Type[] CandidateList {
            get {
                return this.candidateListField;
            }
            set {
                this.candidateListField = value;
                this.RaisePropertyChanged("CandidateList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errors", IsNullable=true, Order=1)]
        public PersonToPersonAuthenticateErrorType[] errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ErrorPmt2Type errorPmt2 {
            get {
                return this.errorPmt2Field;
            }
            set {
                this.errorPmt2Field = value;
                this.RaisePropertyChanged("errorPmt2");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticatePersonPmt2Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AuthenticatePmt2ResponseType authenticatePmt2ResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public AuthenticatePmt2ResponseType AuthenticatePmt2Response {
            get {
                return this.authenticatePmt2ResponseField;
            }
            set {
                this.authenticatePmt2ResponseField = value;
                this.RaisePropertyChanged("AuthenticatePmt2Response");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PosicionGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dPMovilField;
        
        private string gdLatitudField;
        
        private string gdLongitudField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int DPMovil {
            get {
                return this.dPMovilField;
            }
            set {
                this.dPMovilField = value;
                this.RaisePropertyChanged("DPMovil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GdLatitud {
            get {
                return this.gdLatitudField;
            }
            set {
                this.gdLatitudField = value;
                this.RaisePropertyChanged("GdLatitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string GdLongitud {
            get {
                return this.gdLongitudField;
            }
            set {
                this.gdLongitudField = value;
                this.RaisePropertyChanged("GdLongitud");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserInfoGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string branchIdField;
        
        private string transactionIdField;
        
        private string userCodeField;
        
        private string userIPField;
        
        private string userMacField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BranchId {
            get {
                return this.branchIdField;
            }
            set {
                this.branchIdField = value;
                this.RaisePropertyChanged("BranchId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserCode {
            get {
                return this.userCodeField;
            }
            set {
                this.userCodeField = value;
                this.RaisePropertyChanged("UserCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UserIP {
            get {
                return this.userIPField;
            }
            set {
                this.userIPField = value;
                this.RaisePropertyChanged("UserIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UserMac {
            get {
                return this.userMacField;
            }
            set {
                this.userMacField = value;
                this.RaisePropertyChanged("UserMac");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FingerPrintGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string formatPrintField;
        
        private int fingerIdField;
        
        private string fingerBufferField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FormatPrint {
            get {
                return this.formatPrintField;
            }
            set {
                this.formatPrintField = value;
                this.RaisePropertyChanged("FormatPrint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int FingerId {
            get {
                return this.fingerIdField;
            }
            set {
                this.fingerIdField = value;
                this.RaisePropertyChanged("FingerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FingerBuffer {
            get {
                return this.fingerBufferField;
            }
            set {
                this.fingerBufferField = value;
                this.RaisePropertyChanged("FingerBuffer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSSecurIDMatcherSoapChannel : ContingenciaOperador.WSSecurIDMatcher.WSSecurIDMatcherSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSecurIDMatcherSoapClient : System.ServiceModel.ClientBase<ContingenciaOperador.WSSecurIDMatcher.WSSecurIDMatcherSoap>, ContingenciaOperador.WSSecurIDMatcher.WSSecurIDMatcherSoap {
        
        public WSSecurIDMatcherSoapClient() {
        }
        
        public WSSecurIDMatcherSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSecurIDMatcherSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSecurIDMatcherSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSecurIDMatcherSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ContingenciaOperador.WSSecurIDMatcher.AuthenticatePersonPmt2Response MatcherServices_V0R1(ContingenciaOperador.WSSecurIDMatcher.WSSecurIDMatcherEntry DataEntry) {
            return base.Channel.MatcherServices_V0R1(DataEntry);
        }
        
        public System.Threading.Tasks.Task<ContingenciaOperador.WSSecurIDMatcher.AuthenticatePersonPmt2Response> MatcherServices_V0R1Async(ContingenciaOperador.WSSecurIDMatcher.WSSecurIDMatcherEntry DataEntry) {
            return base.Channel.MatcherServices_V0R1Async(DataEntry);
        }
    }
}
